spring.application.name=api-mice-replicacao-backend
server.port=${node.porta}

spring.datasource.url=jdbc:postgresql://localhost:5432/api_mice_replicacao
spring.datasource.username=postgres
spring.datasource.password=masterkey
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

node.id=1
node.host=localhost
node.porta=8080

election.timeout-ms=5000
heartbeat.interval-ms=5000
heartbeat.timeout-ms=15000

webhook.enabled=true
# webhook.security-token=altere-este-token
